WIP DEVX-5712 Feature/selective archive broadcast
opentok/opentok-node pull request #253
Opened 2021-10-15 22:00 UTC by moficodes

#### What is this PR doing?
Adds selective streams to archive and broadcast.

#### How should this be manually tested?

#### What are the relevant tickets?
https://jira.vonage.com/browse/DEVX-5712

2021-11-02 01:50 UTC, jeffswartz requested changes

2021-11-02 01:50 UTC, jeffswartz commented on lib/opentok.js
> +  * @method #patchArchive
This does not match the proposal: https://github.com/opentok/api-review/pull/232/. The proposal has two methods: `OpenTok.addArchiveStream()` and `OpenTok.removeArchiveStream()`.

2021-11-02 01:50 UTC, jeffswartz commented on lib/opentok.js
> +  this.patchBroadcast = function patchBroadcast(broadcastId, options, callback) {
This does not match the proposal: https://github.com/opentok/api-review/pull/232/. The proposal has two methods: `OpenTok.addBroadcastStream()` and `OpenTok.removeBroadcastStream()`.

2021-11-02 02:08 UTC, jeffswartz requested changes
There are merge conflicts.

2021-11-24 05:11 UTC, jeffswartz requested changes
This PR seems to have a lot of changes unrelated to the selective stream archive/broadcast API enhancement. Please add those changes to a separate PR.

2021-11-24 19:42 UTC, moficodes commented
#254 closing since that covers this.
WIll make separate pr with lining fixes.

2021-11-24 19:42 UTC, closed without merging