DEVX-5712 slective stream for archive and broadcast
opentok/opentok-node pull request #254
Opened 2021-11-24 19:40 UTC by moficodes

What is this PR doing?
Adds selective streams to archive and broadcast.

How should this be manually tested?
What are the relevant tickets?
https://jira.vonage.com/browse/DEVX-5712

closing #253 and replacing with this instead

2021-11-30 21:21 UTC, jeffswartz approved these changes

2021-11-30 21:21 UTC, jeffswartz commented on lib/broadcast.js
> +  * from the session being broadcastd.
```suggestion
  * from the session being broadcast.
```

2021-12-09 16:06 UTC, moficodes commented
@jeffswartz

2022-02-13 23:42 UTC, jeffswartz requested changes

2022-02-13 23:42 UTC, jeffswartz commented on lib/broadcast.js
> +*   </ul>
The value is a number, not a string. Should this be:

```suggestion
You can set the maximum duration to a value from 60 (60 seconds) to
36000 (10 hours). The default maximum duration is 4 hours (14,400 seconds).
```

2022-02-13 23:42 UTC, jeffswartz commented on lib/broadcast.js
> +  * broadcasts automatically stop recording after 120 minutes or when all clients have disconnected
```suggestion
  * Broadcasts automatically stop recording after 120 minutes or when all clients have disconnected
```

2022-02-13 23:42 UTC, jeffswartz commented on lib/opentok.js
> +  * Adds a stream to a broadcast that has the streamMode set to manual.
```suggestion
  * Adds a stream to an archive that has the streamMode set to manual.
  * You can call the method repeatedly with the same stream ID, to toggle
  * the stream's audio or video in the archive.
```

2022-02-13 23:42 UTC, jeffswartz commented on lib/opentok.js
> +  * Adds a stream to a broadcast that has the streamMode set to manual.
```suggestion
```suggestion
  * Adds a stream to a broadcast that has the streamMode set to manual.
  * You can call the method repeatedly with the same stream ID, to toggle
  * the stream's audio or video in the broadcast.
```

2022-02-14 06:04 UTC, moficodes reviewed
/lgtm

2022-02-14 06:05 UTC, jeffswartz approved these changes

2022-02-14 06:05 UTC, merged