Feature/force mute
opentok/opentok-node pull request #256
Opened 2022-02-10 20:34 UTC by moficodes

#### What is this PR doing?
remove active flag from forceMuteAll

add active = true in forceMuteAll
add active = false in disableForceMute

2022-02-10 20:42 UTC, moficodes commented
@jeffswartz

2022-02-14 00:56 UTC, jeffswartz requested changes

2022-02-14 00:56 UTC, jeffswartz commented on lib/opentok.js
> +   * Disables force mute
```suggestion
   * Disables the active mute state of the session. After you call this method, new streams
   * published to the session will no longer have audio muted.
   * <p>
   * After you call the {@link OpenTok#forceMuteAll OpenTok.forceMuteAll()} method,
   * any streams published after the call are published with audio muted. When you call the
   * <code>OpenTok.disableForceMute()</code> method, future streams published to the session
   * are not muted (but any existing muted streams remain muted).
```

2022-02-14 01:51 UTC, jeffswartz approved these changes

2022-02-14 01:52 UTC, merged