Feature/audio streamer lite
opentok/opentok-node pull request #261
Opened 2022-03-24 17:53 UTC by moficodes

#### What is this PR doing?
implements audio streamer lite

#### How should this be manually tested?
`npm run test`

#### What are the relevant tickets?
https://jira.vonage.com/browse/OPENTOK-45140

2022-03-25 04:14 UTC, jeffswartz requested changes

2022-03-25 04:14 UTC, jeffswartz commented on lib/opentok.js
> +    callback
This parameter is undocumented.

2022-03-25 04:14 UTC, jeffswartz commented on lib/opentok.js
> +  * @param token(required) The OpenTok token to be used for the Audio Streamer connection to the.
Extra period at the end of this line.

2022-03-25 04:14 UTC, jeffswartz commented on lib/opentok.js
> +  * @return A {@link SipInterconnect} object with the following properties:
Does this return anything? Not a SipInterconnect object.

2022-12-14 18:10 UTC, manchuck approved these changes

2023-02-10 15:41 UTC, dragonmantank approved these changes

2023-02-10 15:44 UTC, merged