Composer experience
opentok/opentok-node pull request #283
Opened 2022-09-15 20:33 UTC by manchuck

#### What is this PR doing?

Adding the render

#### How should this be manually tested?

```js 
opentok.listRenders({}, (err, renders) => {
    if (err) {
        console.log("There was an error")
        console.log(err);
        return;
    }

    console.log(renders);
})

opentok.getRender('<render id>', (err, render) => {
    if (err) {
        console.log("There was an error")
        console.log(err);
        return;
    }

    console.log(render);
})

opentok.startRender(
    {
        sessionId: sessionId,
        token: token,
        url: '<callback url>',
    }, 
    (err, render) => {
        if (err) {
            console.log("There was an error")
            console.log(err);
            return;
        }

        console.log(render);
    }
)

opentok.stopRender('<render id>', (err, render) => {
    if (err) {
        console.log("There was an error")
        console.log(err);
        return;
    }

    console.log(render);
})
```

#### What are the relevant tickets?

[DEVX-6495](https://jira.vonage.com/browse/DEVX-6495)

2022-09-26 14:13 UTC, jeffswartz commented on lib/opentok.js
> +  * Starts rendering an OpenTok session.
Please copy (with any required edits) the docs for the REST method: https://tokbox.com/developer/rest/#starting_experience_composer (for this description and the docs for the options). For example:

```suggestion
  * Starts an Experience Composer for an OpenTok session. The Experience Composer
  * instance is represented as a Render object.
  * For more information, see the
  * <a href="https://tokbox.com/developer/guides/experience-composer/">Experience Composer developer guide</a>.
```

2022-09-26 14:14 UTC, jeffswartz commented on lib/render.js
> +* An object representing an OpenTok render.
```suggestion
* An object representing an Experience Composer renderer.
```

2022-09-26 14:16 UTC, jeffswartz commented on lib/render.js
> +* @property {Number} upddatedAt
```suggestion
* @property {Number} updatedAt
```

2022-09-26 14:18 UTC, jeffswartz commented on lib/render.js
> +*   Current status of for the render. Will be one of `started`, `stopped` or `failed`
The REST docs also mention "starting". Should these be strings (e.g., `"started"`)?

2022-09-26 14:19 UTC, jeffswartz commented on lib/render.js
> +exports.listRenders = (config, options, callback) => {
Please add docs.

2022-09-26 14:19 UTC, jeffswartz commented on lib/render.js
> +exports.getRender = (config, renderId, callback) => {
Please add docs.

2022-09-26 14:20 UTC, jeffswartz commented on lib/render.js
> +exports.startRender = (config, options, callback) => {
Please add docs.

2022-09-26 14:20 UTC, jeffswartz commented on lib/render.js
> +exports.stopRender = (config, renderId, callback) => {
Please add docs.

2022-09-26 14:43 UTC, jeffswartz requested changes

2022-09-26 14:43 UTC, jeffswartz commented on lib/opentok.js
> +  *   </li>
We are not documenting this REST API option. Developers should use account portal to register callbacks. See https://tokbox.com/developer/guides/experience-composer/#configuring-callbacks.

2022-10-03 16:34 UTC, hamzanasir approved these changes
Other than adding the docs that @jeffswartz commented it looks good to me!

2022-10-12 03:56 UTC, jeffswartz approved these changes

2022-11-02 05:56 UTC, jeffswartz commented on lib/opentok.js
> +   * starting with the first render recorded.
```suggestion
   * the method returns up to 1000 renders, starting with the first render recorded.
```

2022-11-02 05:58 UTC, jeffswartz commented on lib/opentok.js
> +   * Stops an OpenTok render that is being rendered.
```suggestion
   * Stops an experience composer that is being rendered.
```

2022-11-02 06:09 UTC, jeffswartz approved these changes

2022-11-07 14:08 UTC, merged