build: updating package
opentok/opentok-node pull request #296
Opened 2023-01-10 20:11 UTC by manchuck

This is updating the `jsonwebtoken` package to fix a critical vulnerability.

2023-01-10 21:12 UTC, dragonmantank requested changes
Instead of passing a `null` and using `true` for the mock class, I think we should pass an empty object instead (and default to one as well)

2023-01-10 21:12 UTC, dragonmantank commented on test/opentok-test.js
> +    .query(query || true)
```suggestion
    .query(query || {})
```

2023-01-10 21:12 UTC, dragonmantank commented on test/opentok-test.js
> +    mockListBroadcastsRequest(null, 400);
```suggestion
    mockListBroadcastsRequest({}, 400);
```

2023-01-11 18:10 UTC, FranciscoCano approved these changes

2023-01-11 18:18 UTC, merged