fix: removing dependancy for node-requests
opentok/opentok-node pull request #311
Opened 2023-09-19 15:36 UTC by manchuck

2023-10-06 17:40 UTC, jeffswartz reviewed
Some tests in opentok_spec.js are failing.

2023-10-06 17:40 UTC, jeffswartz requested changes
https://github.com/opentok/opentok-node/pull/311#pullrequestreview-1662523959

2023-10-09 15:59 UTC, manchuck commented
> Some tests are failing: [#311 (review)](https://github.com/opentok/opentok-node/pull/311#pullrequestreview-1662523959).
> 
> Also, please rev the version (to 2.17.0) in package.json and package-lock.json.

This should only be requested once the PR is ready to merge in. Otherwise the PR will always be rejected as we paly whack-a-mole with the release versions

2023-10-09 16:01 UTC, manchuck commented
> Some tests in opentok_spec.js are failing.

These failures are inconsistent and intermittent. I am not familiar with these tests or how to resolve them. The reason for asking for your review on this PR is because there is not full coverage for all use cases with the SDK. Any guidance from you would be helpful

2023-10-16 21:33 UTC, jeffswartz requested changes
15 tests are failing ("Archiving listArchives should return an array of archives and a total count" and 14 others).

2023-10-16 21:38 UTC, jeffswartz reviewed
When I install packages, I am alerted the `get-func-name` is audited with "high" vulnerability. And `@babel/traverse` is flagged as being critical.  Can we update chai and nyc to update these sub-packages?

2023-10-18 22:33 UTC, jeffswartz requested changes
We need to rev the version of the library (to 2.16.1) in the package.json and package-lock.json files.

2023-10-18 23:17 UTC, jeffswartz commented on lib/archiving.js
> +  request.defaults(_.pick(config, 'proxy', 'timeout'));
@manchuck The failing tests all have this message:

```
Error: Nock: No match for request {
      "method": "post",
      "url": "https://api.opentok.com/v2/project/APIKEY/archive",
      "headers": {
        "user-agent": "OpenTok-Node-SDK/2.16.0",
        "x-opentok-auth": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJBUElLRVkiLCJpc3QiOiJwcm9qZWN0IiwiaWF0IjoxNjk3NjcwOTM3LCJleHAiOjE2OTc2NzEyMzd9.2Ja75MtjsYP4cLvt-uYfXfUhIs07np0SLc9CbuZ2yUY",
        "accept": "application/json",
        "content-length": 190,
        "content-type": "application/x-www-form-urlencoded",
        "host": "api.opentok.com"
      },
      "body": "sessionId=1_MX4xMDB-MTI3LjAuMC4xflR1ZSBKYW4gMjggMTU6NDg6NDAgUFNUIDIwMTR-MC43NjAyOTYyfg&name=test_archive_name&hasAudio=&hasVideo=&outputMode=&layout=&resolution=&streamMode=&multiArchiveTag="
    }
```
Do we need to change something in these lines?

2023-10-23 19:18 UTC, jeffswartz commented on lib/archiving.js
> +      } catch {}
The linter complains that this (and other instances of `catch {}`) results in a parsing error. (Replace with `catch (error) { }`). 

There are already existing linting errors in the main branch. But if you add `/* eslint-env es2018 */` to the top of this file, you will see more linting errors.

2023-10-23 19:24 UTC, jeffswartz approved these changes

2023-10-23 19:29 UTC, jeffswartz requested changes
Please rev the version (to 2.17.0) in package.json and package-lock.json. (I assume we are ready to release this.)

2023-10-23 19:58 UTC, jeffswartz approved these changes

2023-10-23 20:05 UTC, merged